//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/GirishLibrary")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RollField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Roll {
            get {
                return this.RollField;
            }
            set {
                if ((this.RollField.Equals(value) != true)) {
                    this.RollField = value;
                    this.RaisePropertyChanged("Roll");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGirish")]
    public interface IGirish {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/GetData", ReplyAction="http://tempuri.org/IGirish/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/GetData", ReplyAction="http://tempuri.org/IGirish/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/GetStudent", ReplyAction="http://tempuri.org/IGirish/GetStudentResponse")]
        WpfClient.ServiceReference1.Student GetStudent(int roll);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/GetStudent", ReplyAction="http://tempuri.org/IGirish/GetStudentResponse")]
        System.Threading.Tasks.Task<WpfClient.ServiceReference1.Student> GetStudentAsync(int roll);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/SampleMethod", ReplyAction="http://tempuri.org/IGirish/SampleMethodResponse")]
        string SampleMethod(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/SampleMethod", ReplyAction="http://tempuri.org/IGirish/SampleMethodResponse")]
        System.Threading.Tasks.Task<string> SampleMethodAsync(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/ServiceAsyncMethod", ReplyAction="http://tempuri.org/IGirish/ServiceAsyncMethodResponse")]
        string ServiceAsyncMethod(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/ServiceAsyncMethod", ReplyAction="http://tempuri.org/IGirish/ServiceAsyncMethodResponse")]
        System.Threading.Tasks.Task<string> ServiceAsyncMethodAsync(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGirishChannel : WpfClient.ServiceReference1.IGirish, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GirishClient : System.ServiceModel.ClientBase<WpfClient.ServiceReference1.IGirish>, WpfClient.ServiceReference1.IGirish {
        
        public GirishClient() {
        }
        
        public GirishClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GirishClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GirishClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GirishClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WpfClient.ServiceReference1.Student GetStudent(int roll) {
            return base.Channel.GetStudent(roll);
        }
        
        public System.Threading.Tasks.Task<WpfClient.ServiceReference1.Student> GetStudentAsync(int roll) {
            return base.Channel.GetStudentAsync(roll);
        }
        
        public string SampleMethod(string msg) {
            return base.Channel.SampleMethod(msg);
        }
        
        public System.Threading.Tasks.Task<string> SampleMethodAsync(string msg) {
            return base.Channel.SampleMethodAsync(msg);
        }
        
        public string ServiceAsyncMethod(string msg) {
            return base.Channel.ServiceAsyncMethod(msg);
        }
        
        public System.Threading.Tasks.Task<string> ServiceAsyncMethodAsync(string msg) {
            return base.Channel.ServiceAsyncMethodAsync(msg);
        }
    }
}
