//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.GirishServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GirishServiceReference.IGirish")]
    public interface IGirish {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/GetData", ReplyAction="http://tempuri.org/IGirish/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/GetData", ReplyAction="http://tempuri.org/IGirish/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/Process", ReplyAction="http://tempuri.org/IGirish/ProcessResponse")]
        void Process(byte[] array);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGirish/Process", ReplyAction="http://tempuri.org/IGirish/ProcessResponse")]
        System.Threading.Tasks.Task ProcessAsync(byte[] array);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGirishChannel : Test1.GirishServiceReference.IGirish, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GirishClient : System.ServiceModel.ClientBase<Test1.GirishServiceReference.IGirish>, Test1.GirishServiceReference.IGirish {
        
        public GirishClient() {
        }
        
        public GirishClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GirishClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GirishClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GirishClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public void Process(byte[] array) {
            base.Channel.Process(array);
        }
        
        public System.Threading.Tasks.Task ProcessAsync(byte[] array) {
            return base.Channel.ProcessAsync(array);
        }
    }
}
